### ISSUE TITLE
A question about an build error of btpcc-mysql/src 

### ISSUE THREAD

**Issue by Yongmyung-Lee** [meeeejin/2021-advanced-database#1]
Dear. Mijin An 

Hello, I am Yongmyung Lee.

I have a question about building of tpcc-mysql.

Your documentation and video are so easy to understand and clear,
so I could proceed the installation of mysql easily.

But I had a compile error of the tpcc-mysql.
This message is shown below:

matd@matd-vldb:~/data/mysql/tpcc-mysql/src$ make
cc -w -O3 -g -I. `mysql_config --include`  -c load.c
/bin/sh: 1: mysql_config: not found
load.c:19:10: fatal error: mysql.h: No such file or directory
   19 | #include <mysql.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:22: load.o] Error 1

In fact, I could find a soultion that is this link:
https://ohohs.tistory.com/entry/Error-Solution-OSError-mysqlconfig-not-found
It recommended to install "libmysqlclient-dev".

Can I accept this solution? Or could you guide another solution?

Thanks
Yongmyung Lee

**Comment by meeeejin** [comment]
Hi @Yongmyung-Lee,

I updated the [installation guide](https://github.com/meeeejin/2021-advanced-database/blob/master/lab2/reference/tpcc-mysql-install-guide.md#prerequisite) not to have this issue.

Thanks.
